import type { NextPage } from "next";
import MainNavbar from "../components/navbar";
import MainPage from "../components/page";
import Waves from "../waves";
import HeroBanner from "../components/herobanner";
import MainFooter from "../components/footer";
import { useMemo, useState, useEffect } from "react";
import LibraryCard from "../components/librarycard";
import { useRouter } from "next/router";
import Pagination from "../components/pagination";
import { useSession } from "next-auth/react";
import { Poem } from "../types/index";
import { Spinner } from "flowbite-react";
const PublicLibrary: NextPage = () => {
  const [poems, setPoems] = useState<Poem[]>([]);
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(2);
  const { data: session } = useSession();

  const router = useRouter();
  const skip = useMemo(() => Number(router.query.skip) || 0, [router.query]);

  useEffect(() => {
    // if the function runs on the server, the router will be undefined
    if (skip == undefined) return;
    console.log(skip);
    setLoading(true);
    fetch(`/api/poems/get/all?skip=${skip}`, {
      headers: {
        "content-type": "application/json",
      },
    })
      .then((r) => r.json())
      .then((data) => {
        // console.log(data.poems);
        setPoems(data.poems);
        setTotal(data.total);
        setLoading(false);
      })
      .catch((e) => console.log(e));
  }, [skip]);

  return (
    <>
      <Waves height="500px" animate={loading} />
      <MainNavbar />
      <MainPage>
        <HeroBanner>
          <h1 className="text-white text-center text-4xl mb-4 drop-shadow-lg">
            Public Library
          </h1>
          <p className="text-white text-center drop-shadow-lg">
            Poems generated by other users
          </p>
        </HeroBanner>
        {loading ? (
          <div className="bg-white shadow-md p-3 flex flex-col gap-4 rounded-lg w-[200px] text-center mx-auto mb-6">
            <p>Loading poems...</p>
            <Spinner aria-label="Loading poems" color="success" size="xl" />
          </div>
        ) : (
          <Pagination
            take={10}
            skip={skip}
            total={total}
            router={router}
          ></Pagination>
        )}
        <div>
          {!loading &&
            poems &&
            poems.map((poem, i) => {
              return (
                <LibraryCard
                  title={poem.title}
                  text={poem.poem}
                  bookmark={false}
                  key={poem.id}
                  poemId={poem.id}
                  userName={poem.creator.name}
                  userImage={poem.creator.image}
                  sessionId={session ? session.id : undefined}
                  poemImage={poem.image}
                ></LibraryCard>
              );
            })}
        </div>
        {!loading && (
          <Pagination
            take={10}
            skip={skip}
            total={total}
            router={router}
          ></Pagination>
        )}
      </MainPage>
      <MainFooter />
    </>
  );
};

export default PublicLibrary;
